----------------------------------------------------------------------------------
-- Engineer     : Jakob Gross
-- Module Name  : jg_mdio_ctrl
-- Description  : IEEE 802.3 Clause 22 MDIO controller (64-cycle frame).
--
-- Generics:
--   G_CLK_FREQ_HZ   system clock frequency in Hz
--   G_MDC_FREQ_DIV  MDC = CLK / G_MDC_FREQ_DIV, must be even and must not
--                   exceed 2.5 MHz. Example: 125 MHz / 126 = ~992 kHz MDC
--
-- Command interface (ready/valid handshake, transfer when both = '1'):
--   valid_i / ready_o
--   phy_addr_i   5-bit PHY SMI address
--   reg_addr_i   5-bit register address
--   wr_data_i    16-bit write data (ignored for reads)
--   wr_en_i      '1' = write, '0' = read
--
-- Response interface:
--   rd_valid_o / rd_ready_i  handshake, module holds DONE until rd_ready_i='1'
--   rd_data_o                16-bit read result, stable while rd_valid_o='1'
--   ta_err_o                 single-cycle pulse when the PHY does not drive '0'
--                            on the second read turnaround bit, indicating a
--                            missing or non-responsive PHY
--
-- MDIO pins:
--   mdc       clock output
--   mdio_o    data output, connect to IOBUF I
--   mdio_i    data input,  connect to IOBUF O
--   mdio_t    tristate enable, '1' = high-Z, '0' = drive  (matches Xilinx IOBUF T)
--
-- Frame layout (64 MDC cycles):
--   [31: 0]  Preamble   32 bits, all '1'
--   [33:32]  Start      "01"
--   [35:34]  Opcode     "10" read / "01" write
--   [40:36]  PHY addr   5 bits MSB first
--   [45:41]  Reg addr   5 bits MSB first
--   [47:46]  Turnaround write: MAC drives "10", read: MAC tristates
--   [63:48]  Data       16 bits MSB first
--
-- MDC is generated by a free-running counter (0 .. G_MDC_FREQ_DIV-1).
-- State transitions and MDIO output updates occur on mdc_fall_p.
-- Read data is sampled on mdc_rise_p. The PHY drives MDIO within 300 ns
-- after each MDC rising edge. Sampling on the following rising edge gives
-- more than 700 ns of hold margin at 1 MHz MDC, well above the 0 ns minimum.
--
-- Revision:
--   0.01 - File Created
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.NUMERIC_STD.all;

entity jg_mdio_ctrl is
    generic (
        G_CLK_FREQ_HZ  : natural := 125_000_000;
        G_MDC_FREQ_DIV : natural := 126
    );
    port (
        clk   : in std_logic;
        rst_n : in std_logic;

        -- Command interface
        valid_i    : in std_logic;
        ready_o    : out std_logic;
        phy_addr_i : in std_logic_vector(4 downto 0);
        reg_addr_i : in std_logic_vector(4 downto 0);
        wr_data_i  : in std_logic_vector(15 downto 0);
        wr_en_i    : in std_logic;

        -- Response interface
        rd_valid_o : out std_logic;
        rd_ready_i : in std_logic;
        rd_data_o  : out std_logic_vector(15 downto 0);
        ta_err_o   : out std_logic;

        -- MDIO pins
        mdc    : out std_logic;
        mdio_o : out std_logic;
        mdio_i : in std_logic;
        mdio_t : out std_logic
    );
end entity jg_mdio_ctrl;

architecture rtl of jg_mdio_ctrl is

    constant C_MDC_FREQ_HZ : natural := G_CLK_FREQ_HZ / G_MDC_FREQ_DIV;
    constant C_MDC_HALF    : natural := G_MDC_FREQ_DIV / 2;

    -- Minimum bit width to hold 0 .. G_MDC_FREQ_DIV-1
    function f_clog2(n : positive) return natural is
        variable result    : natural := 0;
        variable value     : natural := n - 1;
    begin
        while value > 0 loop
            result := result + 1;
            value  := value / 2;
        end loop;
        return result;
    end function;

    constant C_CNT_W : natural := f_clog2(G_MDC_FREQ_DIV);

    type t_state is (
        IDLE,
        PREAMBLE,   -- 32 cycles: MAC drives '1'
        START,      -- 2 cycles:  "01"
        OPCODE,     -- 2 cycles:  "10" read / "01" write
        PHY_ADDR,   -- 5 cycles:  MSB first
        REG_ADDR,   -- 5 cycles:  MSB first
        TURNAROUND, -- 2 cycles:  write "10" / read tristate
        DATA,       -- 16 cycles: write drives / read samples
        DONE        -- write: back to IDLE, read: wait for rd_ready_i
    );

    type t_reg is record
        state     : t_state;
        mdc_cnt   : unsigned(C_CNT_W - 1 downto 0);
        bit_cnt   : unsigned(4 downto 0);
        shift_out : std_logic_vector(15 downto 0);
        shift_in  : std_logic_vector(15 downto 0);
        phy_addr  : std_logic_vector(4 downto 0);
        reg_addr  : std_logic_vector(4 downto 0);
        wr_en     : std_logic;
        mdio_meta : std_logic; -- first synchronizer stage
        mdio_sync : std_logic; -- second synchronizer stage, used by comb process
    end record;

    constant C_REG_RESET : t_reg := (
        state     => IDLE,
        mdc_cnt => (others => '0'),
        bit_cnt => (others => '0'),
        shift_out => (others => '0'),
        shift_in => (others => '0'),
        phy_addr => (others => '0'),
        reg_addr => (others => '0'),
        wr_en     => '0',
        mdio_meta => '1',
        mdio_sync => '1'
    );

    signal r   : t_reg;
    signal rin : t_reg;

    -- Single-cycle pulses at the first system-clock cycle of each MDC edge
    signal mdc_rise_p : std_logic;
    signal mdc_fall_p : std_logic;

begin

    assert (G_MDC_FREQ_DIV mod 2 = 0)
    report "[jg_mdio_ctrl] G_MDC_FREQ_DIV must be even for 50% MDC duty cycle"
        severity FAILURE;

    assert C_MDC_FREQ_HZ <= 2_500_000
    report "[jg_mdio_ctrl] MDC " & natural'image(C_MDC_FREQ_HZ)
        & " Hz (CLK=" & natural'image(G_CLK_FREQ_HZ)
        & " / DIV=" & natural'image(G_MDC_FREQ_DIV)
        & ") exceeds the 2.5 MHz maximum required by the IEEE 802.3 SMI spec"
        severity FAILURE;

    mdc <= '1' when r.mdc_cnt < to_unsigned(C_MDC_HALF, C_CNT_W) else
        '0';
    ready_o <= '1' when r.state = IDLE else
        '0';
    rd_data_o <= r.shift_in;

    mdc_rise_p <= '1' when r.mdc_cnt = to_unsigned(0, C_CNT_W) else
        '0';
    mdc_fall_p <= '1' when r.mdc_cnt = to_unsigned(C_MDC_HALF, C_CNT_W) else
        '0';

    comb : process (r, valid_i, phy_addr_i, reg_addr_i, wr_data_i, wr_en_i,
        rd_ready_i, mdio_i, mdc_rise_p, mdc_fall_p)
    begin
        rin        <= r;   -- hold all fields, only overrides below take effect
        mdio_t     <= '1'; -- default: MAC releases bus
        mdio_o     <= '1'; -- default: MDIO idles high
        rd_valid_o <= '0';
        ta_err_o   <= '0';

        -- Synchronize async mdio_i into the system clock domain
        rin.mdio_meta <= mdio_i;
        rin.mdio_sync <= r.mdio_meta;

        -- MDC counter: free-running in all states
        if r.mdc_cnt >= to_unsigned(G_MDC_FREQ_DIV - 1, C_CNT_W) then
            rin.mdc_cnt <= (others => '0');
        else
            rin.mdc_cnt <= r.mdc_cnt + 1;
        end if;

        case r.state is

            when IDLE =>
                if valid_i = '1' then
                    rin.phy_addr  <= phy_addr_i;
                    rin.reg_addr  <= reg_addr_i;
                    rin.shift_out <= wr_data_i; -- pre-loaded; avoids an extra cycle in DATA
                    rin.shift_in  <= (others => '0');
                    rin.wr_en     <= wr_en_i;
                    rin.bit_cnt   <= (others => '0');
                    rin.state     <= PREAMBLE;
                    -- mdc_cnt is not reset: MDC runs continuously so there
                    -- is no phase discontinuity between back-to-back transactions.
                end if;

            when PREAMBLE =>
                mdio_t <= '0';
                mdio_o <= '1';
                if mdc_fall_p = '1' then
                    if r.bit_cnt = to_unsigned(31, 5) then
                        rin.bit_cnt <= (others => '0');
                        rin.state   <= START;
                    else
                        rin.bit_cnt <= r.bit_cnt + 1;
                    end if;
                end if;

            when START =>
                mdio_t <= '0';
                mdio_o <= '0' when r.bit_cnt = to_unsigned(0, 5) else
                    '1';
                if mdc_fall_p = '1' then
                    if r.bit_cnt = to_unsigned(1, 5) then
                        rin.bit_cnt <= (others => '0');
                        rin.state   <= OPCODE;
                    else
                        rin.bit_cnt <= r.bit_cnt + 1;
                    end if;
                end if;

                -- Read "10", Write "01"
            when OPCODE =>
                mdio_t <= '0';
                if r.wr_en = '1' then
                    mdio_o <= '0' when r.bit_cnt = to_unsigned(0, 5) else
                        '1';
                else
                    mdio_o <= '1' when r.bit_cnt = to_unsigned(0, 5) else
                        '0';
                end if;
                if mdc_fall_p = '1' then
                    if r.bit_cnt = to_unsigned(1, 5) then
                        rin.bit_cnt <= (others => '0');
                        rin.state   <= PHY_ADDR;
                    else
                        rin.bit_cnt <= r.bit_cnt + 1;
                    end if;
                end if;

            when PHY_ADDR =>
                mdio_t <= '0';
                mdio_o <= r.phy_addr(4 - to_integer(r.bit_cnt));
                if mdc_fall_p = '1' then
                    if r.bit_cnt = to_unsigned(4, 5) then
                        rin.bit_cnt <= (others => '0');
                        rin.state   <= REG_ADDR;
                    else
                        rin.bit_cnt <= r.bit_cnt + 1;
                    end if;
                end if;

            when REG_ADDR =>
                mdio_t <= '0';
                mdio_o <= r.reg_addr(4 - to_integer(r.bit_cnt));
                if mdc_fall_p = '1' then
                    if r.bit_cnt = to_unsigned(4, 5) then
                        rin.bit_cnt <= (others => '0');
                        rin.state   <= TURNAROUND;
                    else
                        rin.bit_cnt <= r.bit_cnt + 1;
                    end if;
                end if;

                -- Write "10", read tristate; turnaround bits are not sampled
                -- Clause 22: first TA bit the MAC releases the bus (Z),
                -- second TA bit the PHY must drive '0'. If it does not,
                -- the bus is floating and ta_err_o is pulsed for one cycle.
            when TURNAROUND =>
                if r.wr_en = '1' then
                    mdio_t <= '0';
                    mdio_o <= '1' when r.bit_cnt = to_unsigned(0, 5) else
                        '0';
                else
                    mdio_t <= '1';
                    -- Check PHY drives '0' on the second turnaround bit.
                    -- Error when bus stays high (PHY absent or non-responsive).
                    if mdc_rise_p = '1' and r.bit_cnt = to_unsigned(1, 5) then
                        ta_err_o <= r.mdio_sync;
                    end if;
                end if;
                if mdc_fall_p = '1' then
                    if r.bit_cnt = to_unsigned(1, 5) then
                        rin.bit_cnt <= (others => '0');
                        rin.state   <= DATA;
                    else
                        rin.bit_cnt <= r.bit_cnt + 1;
                    end if;
                end if;

                -- Write: drive shift_out(15) on every MDC cycle, shift left on fall.
                -- Read:  the PHY drives MDIO within 300 ns after each MDC rising edge.
                --        Sampling on the following rising edge gives more than 700 ns of hold margin.
            when DATA =>
                if r.wr_en = '1' then
                    mdio_t <= '0';
                    mdio_o <= r.shift_out(15);
                    if mdc_fall_p = '1' then
                        if r.bit_cnt = to_unsigned(15, 5) then
                            rin.state <= DONE;
                        else
                            rin.shift_out <= r.shift_out(14 downto 0) & '0';
                            rin.bit_cnt   <= r.bit_cnt + 1;
                        end if;
                    end if;
                else
                    mdio_t <= '1';
                    if mdc_rise_p = '1' then
                        rin.shift_in <= r.shift_in(14 downto 0) & r.mdio_sync;
                    end if;
                    if mdc_fall_p = '1' then
                        if r.bit_cnt = to_unsigned(15, 5) then
                            rin.state <= DONE;
                        else
                            rin.bit_cnt <= r.bit_cnt + 1;
                        end if;
                    end if;
                end if;

            when DONE =>
                if r.wr_en = '1' then
                    rin.state <= IDLE;
                else
                    rd_valid_o <= '1';
                    if rd_ready_i = '1' then
                        rin.state <= IDLE;
                    end if;
                end if;

        end case;

    end process comb;

    seq : process (clk)
    begin
        if rising_edge(clk) then
            if rst_n = '0' then
                r <= C_REG_RESET;
            else
                r <= rin;
            end if;
        end if;
    end process seq;

end architecture rtl;