name: GHDL Simulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ghdl_sim:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install GHDL
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ghdl make
          rm -rf /var/lib/apt/lists/*

      - name: Verify GHDL
        run: ghdl --version

      - name: Simulate jg_mdio_ctrl
        run: make sim_mdio_ctrl

      - name: Simulate lan8720_ctrl
        run: make sim_lan8720_ctrl

      - name: Simulate jg_rmii_to_bytes
        run: make sim_rmii_to_bytes

      - name: Simulate jg_rmii_axis_decoder
        run: make sim_rmii_axis_decoder
